### PR TITLE
Shallow defect analysis

### PR DESCRIPTION
**Pull request by kavanase**
Quoting @adair-nicolson's initial overview:
> Added the ability to easily use `pydefect` to identify shallow defects. When parsing a single defect using `DefectParser.from_paths()`, if the user adds the tag `load_phs_data=True` additional data is loaded from the `vasprun.xml` i.e. projected eigenvalues. Then using `dp.get_perturbed_host_state()` information about the defect level is returned, including an automated attempt at PHS identification. Additionally a plot of the single-particle levels is generated for added verification. Added an example and some additional information to the tips and tricks section of the docs. I added the majority of the functions to the file `doped.utils.phs.py` to keep them out of the way and to allow easy changes to be made if needed when `pydefect/vise` are updated. Starting a draft pull request so can get feedback on if you would want me to rearrange some stuff, plus get those comments while I polish up the final bit.
> 
> Example:
> 
> phs_set_up identifiy_phs

### CODE REVIEW

**Comment by kavanase** [comment]
Does this code also allow IPR analysis @adair-nicolson? (Can't remember what 'P ratio' is here)

**Comment by adair-nicolson** [comment]
> Does this code also allow IPR analysis @adair-nicolson? (Can't remember what 'P ratio' is here)

So P-ratio is a similar-ish metric. P-ratio (participation ratio) is the ratio of the projected orbitals of the neighbouring atoms to the defects site to the sum of all atoms. So for a delocalised states/band states you would expect a small value. But there was a little bug, which is the last thing I need to fix today, related to setting the number of nearest neighbour.

**Comment by adair-nicolson** [comment]
@kavanase I'm going to set ```load_phs_data: Optional[bool] = False``` just to avoid having to redo all of the test case in ```test_analysis.py```. But can work slowly on updating them all afterwards, and then change the default behaviour in a future update

**Comment by kavanase** [comment]
Ok! Which part is it breaking in the analysis tests? (Shouldn't affect other properties being tested?)

**Comment by adair-nicolson** [comment]
Have got round the failed tests by settings the code to skip the trying to do the shallow defect analysis if you don't have the rights files/```vise``` version and returns a warning rather that raising an error. E.g.

```
v_vise = version("vise")
if v_vise <= "0.8.1":
warnings.warn(
                f"You have version {v_vise} of the package `vise`,"
                f" which does not allow the parsing of non-collinear calculations."
                f" You can install the updated version of `vise` from the GitHub repo for this"
                f" functionality. Attempting to load the PHS data has been automatically skipped"
            )
```

so should be able to re-enable the shallow defect analysis as the default behaviour

**Comment by kavanase** [comment]
Looking nice @adair-nicolson! When this gets to the near-completion stage, could you add a short section to the advanced analysis tutorial showing it in action? Thanks!

**Comment by kavanase** [comment]
Docs page looks nice @adair-nicolson! (https://doped--50.org.readthedocs.build/en/50/Tips.html#perturbed-host-states)

Would be nice to include a plot or two (and the original TLD showing the position of the shallow defect level?) if possible! 🤩

**Comment by kavanase** [comment]
@adair-nicolson small thing but just to flag, the plot legend seems to mix up occupied and unoccupied atm

**Comment by kavanase** [comment]
@adair-nicolson I guess this is nearly ready to merge? 😄 

Some things to mention/flag:
- I was running into a few problems when trying this out which I couldn't figure out the issue for at first, but then realised the `pydefect` & `vise` versions both needed to be the most recent ones (Dec 2023) so have updated the requirements to match this.
- `pre-commit` flagged some formatting issues before I could push, so I guess you mightn't have this installed for your local `doped` repo, just fyi!
- I have some small updates to add just in terms of how the warnings are printed with `DefectsParser` when PHS data can't be parsed, and will update the tests accordingly. Will get this done asap and push.
- I'll add one other test case with an interstitial or antisite/substitution. Good to test at least one other case, and also just to confirm my interpretation of the P-ratio is correct (original tips doc said this was orbitals from the defect neighbours, but should be neighbours _plus defect_ (if defect isn't a vacancy) right? Have updated tips to this but would be good to confirm this). 
- Just to note so it doesn't go missing, I think two things left to do are those mentioned above; the addition of the PHS plot & TLD on the tips page and the addition of basically the same example to the advanced analysis tutorial, if you can get to those when you have a chance.
- Tiny thing but on the tips code example `dielectric` was missing, so would fail if a user just copied this and tried with the example data. I updated but couldn't find the dielectric given in your Cu2SiSe3 paper. Doesn't really matter but good for consistency; could you update this value to the correct one for this system?

**Comment by kavanase** [comment]
Ok! That's a bit odd; like in the case where you have an antisite that doesn't move or any interstitial, and the charge density is mostly localised on that atom, then you would get a low P ratio implying a delocalised state when in fact it's highly localised? 🤷 
If it's possible, then yes it would be great if we could have that being consistent, and using the defect plus neighbours in each case. Thanks!

**Comment by kavanase** [comment]
Just to check, I noticed this random statement lost in the code, which currently doesn't do anything. Deleted in the latest commit, but just to flag in case it was intended for anything!

image

**Comment by adair-nicolson** [comment]
@kavanase just a note I don't think this folder has been uploaded to the examples ``bulk_path = "CdTe/CdTe_bulk/vasp_gam/"`` so the interstitial part of the advanced analysis can not be completed.

**Comment by kavanase** [comment]
Ah good spot! Was removed in a previous update because it wasn't used in any of the code/tests, but missed that it was still used in that part of the tutorials. Fixed now in `develop`!

**Comment by kavanase** [comment]
Was playing around with some of this code @adair-nicolson. I noticed it seemed to be far slower at parsing when `load_phs_data = True`, and realise this is due to the Vasprun loading/handling being much slower when `parse_projected_eigen = True` (as needed for PHS analysis). E.g. from about 1 minute to ~10 minutes for loading the 7 example CdTe defects in the repository – actually with all example defects included, it seems like `DefectsParser` is just hanging due to memory overload (can be avoided by reducing `processes`, but waiting a long while...).

I have sped this up a little bit by adjusting the code so that the bulk vasprun should only be loaded once, but still v slow and memory intensive with `parse_projected_eigen = True`. Kind of annoying if the parsing is so slow when PHS data is being parsed – if this can't be improved, then maybe actually better not to parse by default, and make sure we have an easy convenience method to re-parse this data from a `vasprun.xml` later on at a `DefectEntry` level. From your knowledge of this, is there any easy ways to avoid the use of `parse_projected_eigen = True` in the vasprun loading here?

If this info can be pulled from the `PROCAR(.gz)` (which is quicker according to https://github.com/materialsproject/pymatgen/pull/88), then maybe we could add functionality to preferentially parse this data from it if present, otherwise from the `vasprun.xml(.gz)`?

In case it's useful, this is the code I use to profile bottlenecks in the code, which shows which underlying function calls are taking the most time etc:
```python
from cProfile import Profile
from pstats import Stats

with Profile() as pr:
    dp = DefectParser.from_paths(
        defect_path="../../examples/CdTe/Int_Te_3_1/vasp_ncl",
        bulk_path="../../examples/CdTe/CdTe_bulk/vasp_ncl",
        skip_corrections=True,
    )

stats = Stats(pr)
stats.sort_stats("cumulative").print_stats(10)
```

**Comment by kavanase** [comment]
Ok so some progress here at least, with that latest commit the CdTe example data is all parsed fine with no memory crash, taking 2 min 20 seconds on my laptop (compared to 1 minute 4 seconds with `load_phs_data=False`). Not the worst, but would ideally be a bit more efficient. 
I think I can hack the `_parse_projected_eigen()` method for `Vasprun` to be a bit more efficient, so will also try that

**Comment by kavanase** [comment]
Ok with this monkey patch update it drops that parsing time down to ~1 minute 50 seconds. Not the best, but def not the worst and a lot better than before. I think with this, it's good to stick with `load_phs_data` being `True` by default. And worth keeping it in mind if there's any potential improvements in parsing speed that could be achieved down the line.

Just to note, the docstring for `load_phs_data` in `DefectsParser` and `DefectParser.from_paths` doesn't seem to be totally accurate (just that it's actually just loading the necessary data for `DefectEntry.get_perturbed_host_state()` to work, rather than doing this). Could we add a short mention to this docstring portion that the default `load_phs_data = True` significantly increases the parsing time (~30-70%)(– depending on FNV/eFNV/no corrections) due to loading the projected eigenvalues?
```
load_phs_data (bool):
    Automatically determines the band edge states of the defect to determine
    if the defect is a PHS. Also returns single-particle levels and their
    occupation. cite: https://doi.org/10.1103/PhysRevMaterials.5.123803
    Default = True.
```

**Comment by adair-nicolson** [comment]
Yeah, I had noticed that as well. I can test an implementation that uses the ``PROCAR`` if the user has them and will see if that is significantly faster. The original intention of making it use the ``vasprun.xml`` was to avoid the user having to save an additional file.

**Comment by adair-nicolson** [comment]
@kavanase so using the ``PROCAR`` to get the projected eigenvalues I get a 50% speed (loading one defect, no corrections). Will implement a method something so it's tries using the ``PROCAR`` by default, then if it can't find one uses ``vasprun.xml`` but throws a warnings saying will be slower.

**Comment by kavanase** [comment]
Ok cool! I think if the `PROCAR(.gz)` isn't present, but the `vasprun.xml(.gz)` is with the necessary data, then we don't need to throw a warning (probably enough as is 😅 ), but should not in the docstrings and docs that if `PROCAR`s are present then this parsing will be a bit quicker. Thanks!

**Comment by kavanase** [comment]
All tests passing I see @adair-nicolson, nice 😎
Is this ready for review or do you have more stuff to add?

**Comment by adair-nicolson** [comment]
Doing a final check today that everything works with the GitHub version of vise, then should be good for review. Will let you know!

**Comment by adair-nicolson** [comment]
@kavanase was thinking probably worth renaming it from ``phs.py`` to something more informative like ``shallow_defects.py`` or another suggestion if you have one. Will make more sense if we chose to add additional features such as simple models to calculate the binding energy as well

**Comment by kavanase** [comment]
Some suggested refactoring of the function names etc. there @adair-nicolson, to reflect the more general usefulness of this analysis (and also then using `parse_projected_eigen` means we're consistent with `pymatgen`'s terminology for this). Let me know if you're happy with this or have any changes!

Some small things I'll try adding:
- I think we can make parsing of `PROCAR.gz` possible fairly easily, by directly using the `Procar._read(fobj)` function in `easyunfold` with `monty.io.zopen` (as done in `pymatgen` for loading vasp outputs); I'll try add this and then update that test (thanks for adding the `PROCAR` test too btw!)
- For `DefectEntry.get_perturbed_host_state()`, I think it would be good for it to try parse available data in `calculation_metadata["defect_path"]` (& `calculation_metadata["bulk_path"]`) if the data isn't already loaded, before erroring out, so the user has the option to just selectively parse this data later on if only needed for a subset of cases.
- I think I can update this so that `bulk_outcar_phs` is not necessary. I guess likely that this is present in most cases anyway, but in case it's not it'd be good to not require it. As far as I can see, it's just to feed `nelect` and `total_magnetization` to `pydefect`'s `BandEdgeProperties` – neither of which are available via `pymatgen`'s vasprun parser. I have a function already for getting the `nelect` value (`get_neutral_nelect_from_vasprun`) and I think I've figured a way to get `total_magnetization` too, so will try adding this

**Comment by kavanase** [comment]
Ok I've updated `easyunfold` to be able to load `PROCAR.gz` files fine; https://github.com/SMTG-Bham/easyunfold/commit/45d0764cb66cb19be6384877b8a759e93c3ed169

It's not on `conda`, so I'll add its (and the additional `vise`/`pydefect` ones in `doped.utils.eigenvalues`) `import` calls into `try`/`except` catches that give an error message to the user about it not being installed if they try to load a `PROCAR` with it in `doped` (as done e.g. for the `doped.corrections` `import`s). Will see if we can just add it to `conda-forge` in the future.

Quick question @adair-nicolson, do you know if with the `easyunfold` `procar` (which supports SOC calculations), does this avoid the need for `vise` > 0.8.1 for SOC calculations for the eigenvalue analysis?

**Comment by adair-nicolson** [comment]
The reason you need to ``vise`` > 0.8.1 is for this addition where they add a way to find the ho_band_index in the case of a SOC calculation, which is a method belonging to ``BandEdgeProperties``. Older versions miss the first if statement. I could add another monkey patch or do something else to get around it if you thought that best. 

```
def _ho_band_index(self, spin):
        if self._is_non_collinear:
            return round(self._nelect) - 1

        if spin == Spin.up:
            num_occupied_band = (self._nelect + self._magnetization) / 2
        else:
            num_occupied_band = (self._nelect - self._magnetization) / 2

        return round(num_occupied_band) - 1
```

Also, an aside, can't you just use the ``Vasprun`` method ``.parameters.get("NELECT")`` to get the ``nelect``.

**Comment by kavanase** [comment]
Ah ok! If it's just one method that's causing the issue, then might be easiest to just monkey patch now so we have the functionality and don't have to worry about watching `vise` for a new release etc?

And yeah for the `NELECT` issue I've noticed that before and is annoying (why `pymatgen` and other codes all require the `OUTCAR` for getting `NELECT`), but I implemented a way of back-calculating this from the `POTCAR`s in: 
https://doped.readthedocs.io/en/latest/_modules/doped/utils/parsing.html#get_neutral_nelect_from_vasprun
and then if it's a charged defect supercell you just add `-charge` to the neutral `NELECT` as is done in `doped` – though not necessary for the eigenval analysis as this part is only used for the bulk state which should be a neutral calc.

**Comment by kavanase** [comment]
Some updates here @adair-nicolson.
I've implemented most of the targets mentioned above, but still need to update so that the bulk OUTCAR isn't required, so I'll try push forward on that.

With all this updated parsing, for the CdTe example set of 7 defects on the repo, it takes 56 seconds to parse without the eigenvalue data (same as before), and only 60 seconds to parse with this data, so nearly negligible extra cost now in this case (whoop). Likewise with your Cu2SiSe3 defects, takes 26 seconds without eigenvalue data parsing, and 33 seconds with parsing – this is actually the same now, whether parsing PROCARs or vaspruns.

**Comment by kavanase** [comment]
> Ah ok! If it's just one method that's causing the issue, then might be easiest to just monkey patch now so we have the functionality and don't have to worry about watching vise for a new release etc?

Scratch that ☝️  Kumagai just released a new `vise` version:
https://pypi.org/project/vise/#history 🎉

**Comment by kavanase** [comment]
@adair-nicolson I think we're nearly there (_finally_... 😅 ).
One last (hopefully quick) thing:
One or two of the JSON dict comparison tests are failing when now when `vasprun` parsing is used instead of `PROCAR` parsing for Cu2SiSe3. I checked and the plots look ok, and apparently everything in the dict is the same except the `orbital_diff` values, but I can't see what the issue is. I tried adjusting `normalise=True/False` with the `easyunfold` `PROCAR` parsing which changed these values, but also didn't match with the `vasprun` parsing. Would you be able to look into this please? I saw you've set a custom `_orbital_diff` in `eigenvalues.py`. Not sure what's going on here / if it matters

**Comment by kavanase** [comment]
Also a quick question just to confirm, P-ratio does (now) include the defect site itself yeah? Seems to from the outputs I saw, but wanted to confirm

**Comment by kavanase** [comment]
Aaanndd one other last thing to check, I noticed for these plots there tends to be a lot of white space in the plot, as for some reason it only shows some bands close to the band gap, but the y-limits extend beyond this:
image

image

Would it be better to adjust y based on the eigenvalue range shown? You adjust `ylim` in your plotting code, is there any reason not to reduce it compared to the current range?

**Comment by adair-nicolson** [comment]
1. This stems from the fact that the ``vasprun.xml`` stores the data to more significant figures compared to the ``PROCAR`` (and also ``DOSCAR``). The custom ``_orbital_diff`` was cause the test were failing half the time originally due to a floating point error. I.e sometimes orbital diff would be 0.15 vs 0.15000000001. 

Screenshot 2024-03-28 at 09 59 17

2. Yep it should be. The tag ``include_one_site=True`` controls that in ``_coordination`` account for that.

3. Oh, that wasn't working as intended, I can fix that quickly by changing how ``ylim`` is set to. 
```
for ax in emp.axs:
    ax.set_ylim([ymin - 0.25, ymax + 0.75])
```
 The aim was to leave enough white space at the top for the legend so it does not to cover too much data.

**Comment by kavanase** [comment]
Ok!
1. For the `orbital_diff` differences in the band edge states dict output though, it seemed like bigger differences than just significant figures; like `0.012` vs `0.027`? (So maybe not related to the significant figures issue but something else?)
This is what I get when I try to run the tests for this now:
image
image

I added the print statements to make these tests more verbose and a bit easier to debug. The output here is:
```
Testing MgO eigenvalue analysis
Testing Cu2SiSe3 eigenvalue analysis with PROCARs
Testing v_Cu_0 with plot = True
Testing v_Cu_0 with plot = False
Testing Si_i_-1 with plot = True
Testing Cu2SiSe3 parsing and eigenvalue analysis without bulk PROCAR
Testing v_Cu_0 with plot = True
```
So it's getting this failure when it has to fallback to using the bulk vasprun rather than the PROCAR. Would you be able to look into this and see what the issue is?

2. Ok cool!

3. Ok! I dug into this a bit. I've updated to set the y-axis limits to +/-5% of the y-range (matching the default matplotlib behaviour), which is better than a hard eV range just because this can be a bit small or large depending on what the band gap of the system is. I also adjusted the legend settings just a bit (but if you think better a different way lmk!) to account for this (as no longer guaranteed that sticking it in the upper right is best, as it mightn't just be white space). It now uses the default matplotlib best-placement, and I've decreased the opacity of the box to ensure that if there are any points behind it, they're still visible. Also added the `ylims` and `legend_kwargs` options to allow the user to easily customise these (or just have no legend if `legend_kwargs=False`), and added tests for these.

These are some of the default plot outputs now for the test cases:
YTOS_Int_F_-1_eigenvalue_plot_ISPIN_1
Cu2SiSe3_v_Cu_0_eigenvalue_plot
CdTe_v_cd_m2_eigenvalue_plot
CdTe_Te_Cd_+1_eigenvalue_plot

**Comment by kavanase** [comment]
Btw @adair-nicolson,  I updated `orbital_diff` to be normalised in those changes as this seems like the most robust way of doing the orbital comparisons (so either way the `orb_diff` in those JSON files needs to be updated), but maybe there's a reason not to do this?

**Comment by kavanase** [comment]
Ok once that `orb_diff` issue is sorted and tests pass, then this is ready to merge!

**Comment by adair-nicolson** [comment]
@kavanase I'm still pretty sure it's due to the difference in significant figures. Although it's only the third decimal place, that's for each atom, so if you add up all the project eigenvalues for a single band that can make up a sizeable difference, especially in a very large supercell.

If you replace the project eigenvalues loaded with ``Vasprun`` with those loaded with ``Procar``, you get the same result, showing it's not something related to the difference in how band edge states is calculated depending on the files you have saved, but is related to the initial input data.

Screenshot 2024-03-29 at 10 39 04

**Comment by kavanase** [comment]
Ok! Can you update the reference JSONs for this then? 
Before it was passing for the PROCAR parsing but not the vaspruns. If this is the issue, is there some easy easy of fixing?

**Comment by kavanase** [comment]
@adair-nicolson ok so I dug in and saw the significant figures issue you were talking about (I didn't really get the screenshot at first as it seemed it was just replacing the `Vasprun` data with the `PROCAR` data gives the same result as the `PROCAR`s, but I got your point from looking closer); I forgot the `PROCAR` is only 3 decimal places which isn't much in this context and can make a significant difference as you say!

So I added some updates there, just to make the vasprun parsing as efficient as possible (now about 30% quicker overall), and to update the default behaviour to parse the projected eigenvalue data from the vaspruns preferentially rather than `PROCAR`s, as it's more accurate with the 4 decimal places, more convenient for the user, and from testing over all `test_analysis.py` cases, seems to come out only ~5% slower than `PROCAR` parsing now. Also updated the eigenvalue test to use the one JSON file for vasprun/PROCAR parsed data and allow for small numerical differences, rather than using fixed individual JSON reference files. Seems to all be passing locally for me now, so will merge this once the tests above pass! 😃

**Comment by kavanase** [comment]
All tests passing, merging now. Thanks for all your work with this @adair-nicolson! 💪 
Will post a Slack PSA about this during the week too, so ppl know this is now available

**Pull request merged**
