### PR TITLE
`doped` x `py-sc-fermi`

### PR DESCRIPTION
**Pull request by kavanase**

### CODE REVIEW

**Comment by kavanase** [comment]
This is beautiful @alexsquires.

I have some thoughts to share from seeing this in action today:
- For `bulk_vasprun`, would it make sense to rename to `dos_vasprun` (or similar)? Being pedantic, but I think it might help avoid users thinking the bulk supercell vasprun is fine for this, whereas it usually needs to be a relatively well-converged primitive density of states calc (something which I think would be good to note in the tutorial).

- As mentioned, I think the `_format_defect_name()` function from `doped.plotting` could be worth using in the interface plotting tools/examples here. 

- For the `_and_save()` methods, because they're not saving to file but just returning a `DataFrame`, I think the `_and_save()` part could be cut to be more concise and avoid some possible confusion? 

- For `level`, because it's a binary choice of `DefectSpecies` or `DefectChargeState`, I think this would make more sense implemented as a boolean flag (something like `frozen_charge_states = False` (`False` by default, meaning frozen at the defect level) maybe?) – unless there's any plans to change this from a binary option. I think this implementation should still be able to work along with `exceptions` in the same way it currently does.

- The potential efficiency improvements with `py-sc-fermi` you mentioned (whether in the actual implementation and/or from adding `multiprocessing` as in `doped.generation`/`doped.vasp`) would be very nice for making some of these 2D Brouwer diagrams etc nice and quick to generate (particularly for cases like CdTe where one might be interested in the crossover regions (from p to n type) where you need fairly dense sampling to get converged behaviour).
    - On a related point, you mentioned avoiding some of the unnecessary warnings from these looped calculations, that would be great to have too!

**Comment by kavanase** [comment]
Of course, before merging to `master` we should add some tests for this, likely using the data in the example tutorial here. When it's reached a bit of a steady-state I can also redo all the CdTe analysis I did manually for the thesis, and use that as test cases (and add to the tutorial as some further analysis examples)

**Comment by alexsquires** [comment]
I like all of these, and they seem nice and straightforward to implement.
Should be done by end of monday.

**Comment by alexsquires** [comment]
Might add the option to write a csv particularly for the grid search because once you've done it once, you never need to do it again. 

(that's why they have save in there, but yeah, it's unecessary even if they do save a csv)

**Comment by alexsquires** [comment]
- [ ] multiprocessing
- [ ] docstrings
- [ ] tests
- [ ] rename `save functions` and add csv saving
- [ ] suppress warnings
- [ ] dos naming
- [ ] change `level` to boolean
- [ ] basic tutorial
- [ ] advanced searching tutorial

**Comment by kavanase** [comment]
Lovely stuff @alexsquires!
Just fyi, because of the repo cleaning I was doing (removing old unused files from the main branch git history to reduce the repo size when cloning), the histories of this and the main branch have diverged, which is why it's listing ~700 commits here:
image

(I didn't realise I needed to `pull` this branch first too, for it not to diverge 🤦 )
I think the easiest way to fix/deal with this would be to make a new branch & PR (from the current `master`) when this is all ready to go, add the updated files/commits there, and merge that. Can stick with using this PR to track progress and discuss etc for the moment, but when merging will go with that unless there's any other suggestions?

**Pull request closed without merging**
